### ISSUE TITLE
`AddressDisplay`

### ISSUE THREAD

**Issue by leovigna** [owlprotocol/web3-redux#121]
## Description
A component to display an address with useful UX tools.

## Features
  - Display an Ethereum address (or ENS, or stored user-friendly label)
  - Copy to Clipboard Icon
  - Explorer Link
    - Use block explorer link
  - QR Code
    - Display QR Code of address 
  - Label Tag Icon
    - Edit a custom label)
  - Favorite Heart Icon
    - Add to Favorites

**Comment by netanelben** [comment]
https://github.com/owlprotocol/web3-redux/pull/136
